---
title: ggplot2
linktitle: ggplot2
toc: false
type: book
date: "2021-02-01T00:00:00Z"
draft: false
# Add menu entry to sidebar.
# - name: Declare this menu item as a parent with ID `name`.
# - weight: Position of link in menu.
menu:
  rcourse:
    parent: Lesson 3
    weight: 30

weight: 30
---




```{r include=FALSE}
require(tidyverse)
require(ggplot2)

workingdir<-"C:/Users/weste/Documents/GitHub/Rcourse/"

load(paste0(workingdir, "processed_data/county_data_all.rda"))

indiana <- county_data %>% filter(State_fips=="18")

monroecty<-indiana %>% filter(County_fips=="105")
```

In this lesson we will be plotting the data gathered in previous lessons.

```{r}
ggplot(data=indiana)+
  geom_line(aes(x=Year, y=Unemp_rate, colour=County_fips, group=County_fips)) + 
  theme(legend.position="none",
    axis.text.x=element_text(angle=45)) + ylab('Indiana Unemployment Rate by County')
```

```{r}
ggplot(indiana)+
  geom_line(aes(x=Year, y=Unemp_rate, colour=County_fips, group=County_fips), alpha=0.7)+
  geom_line(data=monroecty, aes(x=Year, y=Unemp_rate, colour=County_fips, group=1), alpha=0.9, size=2, colour='black') + 
  theme(legend.position="none",
    axis.text.x=element_text(angle=45)) + ylab('Indiana Unemployment Rate by County')
```