---
# Course title, summary, and position.
linktitle: "Introduction to Coding in R for Economists"
summary: This 3 lecture workshop was put together for Economists at IU to teach basic skills in R.
weight: 2

# Page metadata.
title: "Lesson 1"
date: "2021-01-24T00:00:00Z"
lastmod: "2021-01-24T00:00:00Z"
draft: false  # Is this a draft? true/false
type: docs  # Do not modify.

# Add menu entry to sidebar.
# - name: Declare this menu item as a parent with ID `name`.
# - weight: Position of link in menu.
menu:
  rcourse:
    name: "Lesson 1"
    weight: 3
---
```{r, include=FALSE}
local({
  hook_source <- knitr::knit_hooks$get('source')
  knitr::knit_hooks$set(source = function(x, options) {
    x <- xfun::split_lines(x)
    n <- nchar(x, 'width')
    i <- seq_along(x)  # line numbers
    n <- n + nchar(i)
    s <- knitr:::v_spaces(max(n) - n)
    x <- paste(x, s, '  # ', i, sep = '', collapse = '\n')
    hook_source(x, options)
  })
})
```

## Project Organization

Before we get started, let's set up a folder for our project and create subfolders to keep things organized. For this project I recommend the following subfolders, which are a good minimum for organizing any project:

- raw_data: This is where we will put our `preprocessed' data we will be getting from MIT Election Lab.
- scripts: Where we will save all of our R-scripts in this folder
- processed_data: If we want to save some intermediate data steps between raw data and our output.
- tables: Any tex tables we generate we will save to this folder
- figures: Any figures we generate we will save to this folder
- tex: Where we can have our paper and/or presentations

You can make more folders if you feel it keeps you organized. The main point I want to make here is it is well worth your time to think about how you want to organize your project. Oftentimes if we jump right in without a plan, things become a jumbled mess. (If you want to go further with your organization strategies, I recommend looking into waf, specifically check out [Templates for Reproducible Research Projects in Economics](https://econ-project-templates.readthedocs.io/en/stable/index.html).)

My project folder now looks like this:
**Insert image of folder**

## Getting Data
Let's start by downloading [Senate data from MIT Election Lab's website](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/PEJ5QU#). Let's choose the csv format and save it in your raw_data folder. Next let's download [House of Representatives data from MIT Election Lab](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IG0UN2) again in csv format.

## Reading in the data
Let's open up a blank R script. 




